"""empty message

Revision ID: 16cb33c67ef1
Revises: e61bfa5201f0
Create Date: 2023-12-19 19:15:04.468850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cb33c67ef1'
down_revision = 'e61bfa5201f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('default_pic',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('default_pic',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
