"""empty message

Revision ID: 280a6edd5460
Revises: 16cb33c67ef1
Create Date: 2023-12-19 22:37:21.702496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280a6edd5460'
down_revision = '16cb33c67ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trail_imagesurl', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.drop_column('trail_imagesurl')

    # ### end Alembic commands ###
