"""empty message

Revision ID: 51f7984b2a82
Revises: 16cb33c67ef1
Create Date: 2023-12-19 23:22:01.709519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f7984b2a82'
down_revision = '16cb33c67ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trail_images')
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trail_imagesurl', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trails', schema=None) as batch_op:
        batch_op.drop_column('trail_imagesurl')

    op.create_table('trail_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img_src', sa.VARCHAR(length=255), nullable=False),
    sa.Column('trail_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
