{
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [117.39671, 40.04425]
			},
			"properties": {
				"name": "Dule Temple (\u72EC\u4E50\u5BFA)",
				"ele": "28.0",
				"desc": "Some surviving wooden buildings here date back to AD 984. In AD 755, the rebel general An Lushan held a rally here before going on to launch one of the bloodiest conflicts in history. You can catch a taxi from outside the temple, but there are buses."
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [117.40066, 40.04367]
			},
			"properties": {
				"name": "Jixiang Drum Tower",
				"ele": "25.0"
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [117.40052, 40.0429]
			},
			"properties": {
				"name": "Jixiang Marketplace",
				"ele": "25.0",
				"desc": "Pretty nice street catering to tourists. Snacks, drinks, souvenirs, and a pretty nice town square with an underground shopping centre. The rest of Jixian is less photogenic."
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "MultiLineString",
				"coordinates": [[[117.39602, 40.04413, 27.0], [117.39623, 40.04406, 27.0], [117.39631, 40.04404, 27.0], [117.39639, 40.04401, 28.0], [117.39646, 40.04399, 28.0], [117.39651, 40.04397, 28.0], [117.39658, 40.04394, 28.0], [117.39662, 40.0439, 28.0], [117.39666, 40.04387, 28.0], [117.39673, 40.04387, 29.0], [117.39679, 40.0439, 28.0], [117.39686, 40.04394, 28.0], [117.3969, 40.04399, 28.0], [117.39693, 40.04405, 28.0], [117.39695, 40.0441, 28.0], [117.39691, 40.04413, 28.0], [117.39687, 40.04417, 28.0], [117.39688, 40.04422, 28.0], [117.39691, 40.04427, 28.0], [117.39693, 40.04432, 28.0], [117.39693, 40.04437, 28.0], [117.39694, 40.04442, 28.0], [117.39693, 40.04448, 29.0], [117.39692, 40.04453, 29.0], [117.39693, 40.04458, 29.0], [117.39695, 40.04463, 29.0], [117.39693, 40.04468, 29.0], [117.39688, 40.04471, 29.0], [117.39681, 40.04471, 29.0], [117.39675, 40.04471, 29.0], [117.39668, 40.04471, 29.0], [117.39661, 40.04469, 29.0], [117.39654, 40.04465, 29.0], [117.3965, 40.04461, 28.0], [117.39648, 40.04455, 28.0], [117.39648, 40.0445, 28.0], [117.39648, 40.04445, 28.0], [117.39644, 40.0444, 28.0], [117.39642, 40.04436, 28.0], [117.39642, 40.04429, 28.0], [117.39639, 40.04424, 28.0], [117.39635, 40.04421, 27.0], [117.39627, 40.04419, 27.0], [117.3962, 40.04419, 27.0], [117.39616, 40.04419, 27.0], [117.39602, 40.04413, 27.0]]],
				"bbox": [117.39695, 40.04471, 117.39602, 40.04387]
			},
			"properties": {
				"name": "Dule Temple",
				"desc": "Generated by AllTrails https://www.alltrails.com/"
			}
		}
	]
}
